from typing import Protocol, Optional


class Store(Protocol):
    # --- Sessions / Active Rides ---
    def get_session(self, session_id: str) -> Optional[dict]: ...
    def get_active_session_for_user(self, user_id: str) -> Optional[tuple[str, dict]]: ...
    def get_all_active_sessions(self) -> dict[str, dict]: ...
    def put_session(self, session_id: str, data: dict) -> None: ...
    def delete_session(self, session_id: str) -> None: ...

    # --- Ride History ---
    def get_ride_history(self, user_id: str) -> list[dict]: ...
    def append_ride(self, user_id: str, ride: dict) -> None: ...

    # --- Users ---
    def get_user(self, user_id: str) -> Optional[dict]: ...
    def get_all_users(self) -> list[dict]: ...
    def put_user(self, user_id: str, data: dict) -> None: ...
    def update_user(self, user_id: str, updates: dict) -> None: ...
